name: build & test (clang, gcc, MSVC)

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Latest gcc",
            os: ubuntu-latest,
            cmake-preset: "gcc-release",
            cmake-vars: "-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake"
          }
          - {
            name: "Ubuntu Latest clang",
            os: ubuntu-latest,
            cmake-preset: "clang-release",
            cmake-vars: "-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake"
          }
          - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cmake-preset: "msvc-release",
            cmake-vars: "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_TOOLCHAIN_FILE='vcpkg/scripts/buildsystems/vcpkg.cmake'"
          }

    steps:
    - name: Install ninja (Windows)
      if: matrix.config.os == 'windows-latest'
      run: choco install ninja
    - name: Install ninja (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      run: sudo apt install ninja-build
    - uses: actions/checkout@v4

    - uses: rui314/setup-mold@v1

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: caa7579a1c48e2ca770f6ccf98cb03db95642631

    - uses: hendrikmuhs/ccache-action@v1.2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DENABLE_TESTS=ON -DMNEMOCEAN_USE_BOOST_RANDOM=ON ${{ matrix.config.cmake-vars }} --preset="${{ matrix.config.cmake-preset }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

